name:                discord-bot
version:             0.1.0.0
github:              "BorisNikulin/discord-bot"
license:             BSD3
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2019 Boris Nikulin"

extra-source-files:
    - README.md
    - secrets/*

description: Please see the README on GitHub at <https://github.com/BorisNikulin/simple#readme>

dependencies:
    - base >= 4.7 && < 5
    - discord-haskell
    - polysemy
    - text >= 1.2.3 && < 1.2.4
    - aeson >= 1.3.1.1 && < 1.5
    - megaparsec >= 7.0 && < 7.1
    - random >= 1.1 && < 1.2
    - co-log-core
    - co-log
    - co-log-polysemy

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - BlockArguments
    # polysemy
    - DataKinds
    - FlexibleContexts
    - GADTs
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fno-warn-tabs
    # polysemy
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively

library:
    source-dirs: src

executables:
    discord-bot-exe:
        main:                Main.hs
        source-dirs:         app
        dependencies:
            - discord-bot
