name:                discord-bot
version:             0.1.0.0
github:              "BorisNikulin/discord-bot"
license:             BSD3
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2019 Boris Nikulin"

extra-source-files:
    - README.md
    - secrets/*

description: Please see the README on GitHub at <https://github.com/BorisNikulin/simple#readme>

dependencies:
    - base >= 4.7 && < 5
    - discord-haskell
    - polysemy
    - text >= 1.2.3 && < 1.2.4
    - aeson >=1.3.1.1 && <1.5

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - MultiWayIf
    - BlockArguments
     # polysemy
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

library:
    source-dirs: src

executables:
    discord-bot-exe:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
            - -fno-warn-tabs
             # polysemy
            - -O2
            - -flate-specialise
            - -fspecialise-aggressively
        dependencies:
            - discord-bot
