name:                discord-bot
version:             0.1.0.0
github:              "BorisNikulin/discord-bot"
license:             BSD3
author:              "Boris Nikulin"
maintainer:          "NikulinBE@gmail.com"
copyright:           "2019 Boris Nikulin"

extra-source-files:
    - README.md
    - secrets/*

description: Please see the README on GitHub at <https://github.com/BorisNikulin/discord-bot#readme>

dependencies:
    - base >= 4.7 && < 5
    - discord-haskell
    - polysemy
    - text >= 1.2.3 && < 1.2.4
    - aeson >= 1.3.1.1 && < 1.5
    - megaparsec >= 7.0 && < 7.1
    - co-log-core
    - co-log
    - co-log-polysemy
    - random-fu >= 0.2.5.0 && <0.3.0.0
    - polysemy-RandomFu

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - BlockArguments
    # polysemy
    - DataKinds
    - FlexibleContexts
    - GADTs
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies


library:
    source-dirs: src
    ghc-options:
        - -Wall
        - -Wcompat
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wredundant-constraints
        - -fno-warn-tabs
        # polysemy
        - -O2
        - -flate-specialise
        - -fspecialise-aggressively

executables:
    discord-bot-exe:
        main:                Main.hs
        source-dirs:         app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
            - -fno-warn-tabs
            # polysemy
            - -O2
            - -flate-specialise
            - -fspecialise-aggressively
        dependencies:
            - discord-bot
