resolver: lts-13.25

allow-newer: true

packages:
    - .

extra-deps:
    - discord-haskell-0.8.3

    # copied from
    # https://github.com/polysemy-research/polysemy/blob/ac6d7b312114863987f103871df54b2a5d1fe7d8/stack.yaml
    - polysemy-1.1.0.0
    - aeson-1.4.3.0
    - bifunctors-5.5.4
    - dump-core-0.1.3.2
    - first-class-families-0.5.0.0
    - ghc-lib-0.20190204
    - inspection-testing-0.4.2
    - loopbreaker-0.1.1.0
    - monadLib-3.9
    - th-abstraction-0.3.1.0
    - unagi-chan-0.4.1.0
    - type-errors-0.2.0.0
    - type-errors-pretty-0.0.0.0

    -
        git: https://github.com/kowainik/co-log.git
        commit: e06b90f3934f9e75558586618c23266245a2fef6
        subdirs:
            - co-log-core
            - co-log
            - co-log-polysemy
    - ansi-terminal-0.9.1
    - chronos-1.0.5
    - torsor-0.1
    - typerep-map-0.3.2

    - polysemy-RandomFu-0.4.0.0
    - polysemy-zoo-0.5.0.1
    - polysemy-plugin-0.2.3.0
