resolver: lts-13.25

packages:
    - .

extra-deps:
    - discord-haskell-0.8.3

    # copied from https://github.com/isovector/polysemy/blob/master/stack.yaml
    - polysemy-0.4.0.0
    - aeson-1.4.3.0
    - bifunctors-5.5.4
    - dump-core-0.1.3.2
    - first-class-families-0.5.0.0
    - ghc-lib-0.20190204
    - inspection-testing-0.4.2
    - monadLib-3.9
    - th-abstraction-0.3.1.0

    -
        git: https://github.com/kowainik/co-log.git
        commit: 744504305c5e44249a6606a3ba5395ba484a1cde
        subdirs:
            - co-log-core
            - co-log
            - co-log-polysemy
    - ansi-terminal-0.9.1
    - chronos-1.0.5
    - torsor-0.1
    - typerep-map-0.3.2

    - polysemy-RandomFu-0.2.0.0
    - polysemy-zoo-0.3.0.0
    - polysemy-plugin-0.2.1.0
