resolver: lts-13.25

packages:
    - .

extra-deps:
    - discord-haskell-0.8.3
    - polysemy-0.4.0.0
    # copied from https://github.com/isovector/polysemy/blob/master/stack.yaml
    - aeson-1.4.3.0
    - bifunctors-5.5.4
    - dump-core-0.1.3.2
    - first-class-families-0.5.0.0
    - ghc-lib-0.20190204
    - inspection-testing-0.4.2
    - monadLib-3.9
    - th-abstraction-0.3.1.0
